--Helpful card database

mythodex = {
  { id = 1, name = "Wooden Cow", cost = 1, power = 1, text = "No unique powers." },
  { id = 2, name = "Pegasus", cost = 3, power = 5, text = "No unique powers." },
  { id = 3, name = "Minotaur", cost = 5, power = 9, text = "No unique powers." },
  { id = 4, name = "Titan", cost = 6, power = 12, text = "No unique powers." },
  { id = 5, name = "Zeus", cost = 8, power = 10, text = "When Revealed: Lower the power of each card in your opponent's hand by 1." },
  { id = 6, name = "Ares", cost = 3, power = 0, text = "When Revealed: Gain +2 power for each enemy card here." },
  --{ id = 7, name = "Medusa", cost = 3, power = 4, text = "When ANY other card is played here, lower that card's power by 1." },
  --{ id = 8, name = "Cyclops", cost = 3, power = 4, text = "When Revealed: Discard your other cards here, gain +2 power for each discarded." },
  --{ id = 9, name = "Poseidon", cost = 6, power = 8, text = "When Revealed: Move away an enemy card here with the lowest power." },
  { id = 10, name = "Artemis", cost = 3, power = 3, text = "When Revealed: Gain +5 power if there is exactly one enemy card here." },
  { id = 11, name = "Hera", cost = 6, power = 4, text = "When Revealed: Give cards in your hand +1 power." },
  { id = 12, name = "Demeter", cost = 1, power = 1, text = "When Revealed: Both players draw a card." },
  --{ id = 13, name = "Hades", cost = 7, power = 8, text = "When Revealed: Gain +2 power for each card in your discard pile." },
  { id = 14, name = "Hercules", cost = 8, power = 8, text = "When Revealed: Doubles its power if its the strongest card here." },
  { id = 15, name = "Dionysus", cost = 3, power = 2, text = "When Revealed: Gain +2 power for each of your other cards here." },
  --{ id = 16, name = "Hermes", cost = 1, power = 1, text = "When Revealed: Moves to another location." },
  --{ id = 17, name = "Hydra", cost = 2, power = 3, text = "Add two copies to your hand when this card is discarded." },
  --{ id = 18, name = "Ship of Theseus", cost = 2, power = 2, text = "When Revealed: Add a copy with +1 power to your hand." },
  --{ id = 19, name = "Sword of Damocles", cost = 7, power = 16, text = "End of Turn: Loses 1 power if not winning this location." },
  { id = 20, name = "Midas", cost = 5, power = 3, text = "When Revealed: Set ALL cards here to 3 power." },
  { id = 21, name = "Aphrodite", cost = 2, power = 3, text = "When Revealed: Lower the power of each enemy card here by 1." },
  --{ id = 22, name = "Athena", cost = 5, power = 8, text = "Gain +1 power when you play another card here." },
  --{ id = 23, name = "Apollo", cost = 1, power = 1, text = "When Revealed: Gain +1 mana next turn." },
  --{ id = 24, name = "Hephaestus", cost = 3, power = 4, text = "When Revealed: Lower the cost of 2 cards in your hand by 1." },
  --{ id = 25, name = "Persephone", cost = 4, power = 10, text = "When Revealed: Discard the lowest power card in your hand." },
  --{ id = 26, name = "Prometheus", cost = 5, power = 8, text = "When Revealed: Draw a card from your opponent's deck." },
  { id = 27, name = "Pandora", cost = 3, power = 7, text = "When Revealed: If no ally cards are here, lower this card's power by 5." },
  --{ id = 28, name = "Icarus", cost = 2, power = 2, text = "End of Turn: Gains +1 power, but is discarded when its power is greater than 7." },
  --{ id = 29, name = "Iris", cost = 7, power = 6, text = "End of Turn: Give your cards at each other location +1 power if they have unique powers." },
  --{ id = 30, name = "Nyx", cost = 4, power = 4, text = "When Revealed: Discards your other cards here, add their power to this card." },
  --{ id = 31, name = "Altas", cost = 4, power = 7, text = "End of Turn: Loses 1 power if your side of this location is full." },
  --{ id = 32, name = "Daedalus", cost = 2, power = 2, text = "When Revealed: Add a Wooden Cow to each other location." },
  --{ id = 33, name = "Helios", cost = 6, power = 16, text = "End of Turn: Discard this." },
  --{ id = 34, name = "Mnemosyne", cost = 2, power = 0, text = "When Revealed: Add a copy of the last card you played to your hand." },
}